# Form implementation generated from reading ui file 'formbuild.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(324, 275)
        Form.setStyleSheet("")
        self.name_input = QtWidgets.QLineEdit(parent=Form)
        self.name_input.setGeometry(QtCore.QRect(160, 30, 101, 21))
        self.name_input.setObjectName("name_input")
        self.name_label = QtWidgets.QLabel(parent=Form)
        self.name_label.setGeometry(QtCore.QRect(30, 30, 101, 16))
        self.name_label.setObjectName("name_label")
        self.attempt_label = QtWidgets.QLabel(parent=Form)
        self.attempt_label.setGeometry(QtCore.QRect(30, 60, 131, 16))
        self.attempt_label.setObjectName("attempt_label")
        self.score1_label = QtWidgets.QLabel(parent=Form)
        self.score1_label.setGeometry(QtCore.QRect(30, 90, 60, 16))
        self.score1_label.setObjectName("score1_label")
        self.score2_label = QtWidgets.QLabel(parent=Form)
        self.score2_label.setGeometry(QtCore.QRect(150, 90, 60, 16))
        self.score2_label.setObjectName("score2_label")
        self.attempt_input = QtWidgets.QLineEdit(parent=Form)
        self.attempt_input.setGeometry(QtCore.QRect(160, 60, 101, 21))
        self.attempt_input.setObjectName("attempt_input")
        self.score1_input = QtWidgets.QLineEdit(parent=Form)
        self.score1_input.setGeometry(QtCore.QRect(90, 90, 51, 21))
        self.score1_input.setObjectName("score1_input")
        self.score2_input = QtWidgets.QLineEdit(parent=Form)
        self.score2_input.setGeometry(QtCore.QRect(210, 90, 51, 21))
        self.score2_input.setObjectName("score2_input")
        self.score5_label = QtWidgets.QLabel(parent=Form)
        self.score5_label.setGeometry(QtCore.QRect(30, 150, 60, 16))
        self.score5_label.setObjectName("score5_label")
        self.score6_label = QtWidgets.QLabel(parent=Form)
        self.score6_label.setGeometry(QtCore.QRect(150, 150, 60, 16))
        self.score6_label.setObjectName("score6_label")
        self.score6_input = QtWidgets.QLineEdit(parent=Form)
        self.score6_input.setGeometry(QtCore.QRect(210, 150, 51, 21))
        self.score6_input.setObjectName("score6_input")
        self.score5_input = QtWidgets.QLineEdit(parent=Form)
        self.score5_input.setGeometry(QtCore.QRect(90, 150, 51, 21))
        self.score5_input.setObjectName("score5_input")
        self.score3_label = QtWidgets.QLabel(parent=Form)
        self.score3_label.setGeometry(QtCore.QRect(30, 120, 60, 16))
        self.score3_label.setObjectName("score3_label")
        self.score4_label = QtWidgets.QLabel(parent=Form)
        self.score4_label.setGeometry(QtCore.QRect(150, 120, 60, 16))
        self.score4_label.setObjectName("score4_label")
        self.score4_input = QtWidgets.QLineEdit(parent=Form)
        self.score4_input.setGeometry(QtCore.QRect(210, 120, 51, 21))
        self.score4_input.setObjectName("score4_input")
        self.score3_input = QtWidgets.QLineEdit(parent=Form)
        self.score3_input.setGeometry(QtCore.QRect(90, 120, 51, 21))
        self.score3_input.setObjectName("score3_input")
        self.output_label = QtWidgets.QLabel(parent=Form)
        self.output_label.setGeometry(QtCore.QRect(130, 240, 71, 20))
        self.output_label.setStyleSheet("QLabel { color: red }")
        self.output_label.setObjectName("output_label")
        self.submit_button = QtWidgets.QPushButton(parent=Form)
        self.submit_button.setGeometry(QtCore.QRect(70, 200, 171, 32))
        self.submit_button.setObjectName("submit_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_label.setText(_translate("Form", "Student Name:"))
        self.attempt_label.setText(_translate("Form", "No of attempts (1-6):"))
        self.score1_label.setText(_translate("Form", "Score 1:"))
        self.score2_label.setText(_translate("Form", "Score 2:"))
        self.score5_label.setText(_translate("Form", "Score 5:"))
        self.score6_label.setText(_translate("Form", "Score 6:"))
        self.score3_label.setText(_translate("Form", "Score 3:"))
        self.score4_label.setText(_translate("Form", "Score 4:"))
        self.output_label.setText(_translate("Form", "Submitted"))
        self.submit_button.setText(_translate("Form", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
